# Generated by Django 4.2.6 on 2024-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddata',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
