# Generated by Django 4.2.6 on 2024-02-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_saveddata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddata',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
