# Generated by Django 4.2.6 on 2024-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_saveddata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddata',
            name='author',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
