# Generated by Django 4.2.6 on 2024-02-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_saveddata_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddata',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
